import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/server.ts',
    'src/auth.ts',
    'src/auth-tools.ts',
    'src/graph-client.ts',
    'src/graph-tools.ts',
    'src/cli.ts',
    'src/logger.ts',
    'src/oauth-provider.ts',
    'src/version.ts',
    'src/generated/hack.ts',
    'src/generated/endpoint-types.ts',
    'src/generated/client.ts',
    'src/lib/microsoft-auth.ts',
    'src/endpoints.json',
  ],
  format: ['esm'],
  target: 'es2020',
  outDir: 'dist',
  clean: true,
  bundle: false,
  splitting: false,
  sourcemap: false,
  dts: false,
  publicDir: false,
  onSuccess: 'chmod +x dist/index.js',
  loader: {
    '.json': 'copy',
  },
  noExternal: [],
  external: [
    '@azure/msal-node',
    '@modelcontextprotocol/sdk',
    'commander',
    'dotenv',
    'express',
    'js-yaml',
    'keytar',
    'winston',
    'zod',
  ],
});
